### ISSUE TITLE
Messages - Truncating Currency when IBC

### ISSUE THREAD

**Issue by forgxyz** [MetricsDAO/terra_dbt#31]
The regex splitting amount and currency from `amount` in the messages model is incorrectly truncating IBC Currencies early to just `ibc`. For example, the following is axlUSCD `ibc/B3504E092456BA618CC28AC671A71FB08C6CA0FD0BE7C8A5B5A3E2DD933CC9E4`, but the REGEX is splitting at the `/` and returning just `ibc` as the currency.

**Comment by forgxyz** [comment]
Example tx `E3CC4DD3B466E248574D874856491085905517D57BDA182403FF6065CD22CDA2`

In transaction response:
<img width="290" alt="Screen Shot 2022-10-18 at 09 26 36" src="https://user-images.githubusercontent.com/58153492/196474554-273af021-f3ad-40f7-9276-dc2fc565ae50.png">

As parsed in messages:
<img width="282" alt="Screen Shot 2022-10-18 at 09 26 01" src="https://user-images.githubusercontent.com/58153492/196474561-5573051f-e507-4c4a-bba5-0b9a12fba928.png">

**Comment by robel91** [comment]
what was the REGEX supposed to return other than ibc?

**Comment by D0R11** [comment]
Taking this one out with Patrick shadowing on this one
