### ISSUE TITLE
Governance Votes - Silver & Core 

### ISSUE THREAD

**Issue by jhuhnke** [MetricsDAO/terra_dbt#38]
We need a silver layer for Governance Votes with a core view. This table will be downstream of the messages model (https://github.com/MetricsDAO/terra_dbt/issues/8 ) and should focus on how individual wallets and validators are voting on governance proposals. 

### To Do 
- [ ]  Assign primary & secondary analysts
- [ ]  Design the schema for this table
- [ ]  Get confirmation on schema
- [ ]  Build schema
- [ ]  Schema build review
- [ ]  Submit Pull Request for review by pod

### Direction 
Governance Votes is a common curated table and many examples can be found in the Flipside data tables, most notably in the [Osmosis database](https://github.com/FlipsideCrypto/osmosis-models/blob/main/models/silver/silver__governance_votes.sql).

The suggested schema includes the following tables and tests:
<html>
<body>

Column | Data Type | Tests | Documentation
-- | -- | -- | --
block_id | number | Unique, not null, sequence gaps, number format | Also known as block height. The block_id, which indicates the length of the blockchain, increases after the addition of each new block.
block_timestamp | timestamp | One day recent, not null, timestamp format | The date and time the block was recorded.
blockchain | string | not null, string/varchar format | The name of the blockchain.
chain_id | string | not null, string/varchar format | The version of the blockchain.
tx_id | string | not null, string/varchar format | A unique key that identifies a transaction. Called "TxHash" on block explorers.
tx_succeeded | boolean | not null | TRUE if the transaction was successful, FALSE otherwise.
voter | string | not null, string/varchar format | The address of the wallet that is casting the vote.
proposal_id | number | not null, number format, no gaps test | An ordered, numerical ID that corresponds to the proposal being voted on. 
vote_option | number | not null, number format | How the user voted on the proposal. 
vote_weight | number | not null, number format | The percentage of their stake that the wallet used to cast their vote. 

</body>
</html>

Note: It would be valuable to provide either a dimensional table that matches the numbers in the vote option column to options ( 1 = 'yes', ...), provide additional documentation that describes this, or to add an additional column in this table containing a text vote option. 

### Contribution Reward
Per the S3 approach, this falls into the project category and contribution incentive will be handled through [Coordinape](https://coordinape.com/). Expected collaboration is 3-4 individuals with a primary Analyst, primary PR Reviewer and possible secondaries for either the Analyst or Review side of the work.

Issue reward pool: $1,200 in LUNA (token amount determined at time of payment)

**Comment by eevui** [comment]
I'd like to jump on this!

**Comment by jhuhnke** [comment]
@eevui - sounds good! I will assign the issue to you as the primary analyst

**Comment by eevui** [comment]
MetricsDAO curation grant proposal https://terrasco.pe/mainnet/address/terra1sjgx7q6mx9e5jjg8dcm498w7reuzufghqvucc8d7d3ad4z2fra4q9l574a

Can refer to this contract as a starting point to gather governance txs

**Comment by eevui** [comment]
Proposal tx: https://terrasco.pe/mainnet/tx/06FF8650F2C0E4AD9E1E4B15F62774CAA515CADA0F646FC994574437BDC60458

Yes vote: https://terrasco.pe/mainnet/tx/3ADA5E3294C19805246C49C467FE2DF741E572C5AAEEDE98655694CB1F7EB06F

Votes are simple type MsgVote with the option of yes, no, no with veto, or abstain.

"If a delegator does not specify a vote with their staked Luna, their vote defaults to the vote cast by the validator their Luna is staked to. Delegators can override a validator's vote at any time during the [voting period](https://docs.terra.money/develop/module-specifications/spec-governance#voting-period) by [voting with their staked Luna](https://docs.terra.money/learn/terra-station/governance#vote-on-a-proposal)." [^1]

The vote weight is the amount of LUNA staked, but this value could change as the delegator could make a vote on their own.

[^1]: https://docs.terra.money/develop/module-specifications/spec-governance#tallying

**Comment by jhuhnke** [comment]
@eevui - looks like a good transaction to build on. Seems like Terra has "vote_option_yes", "vote_option_no," etc instead of numbers that correspond to those options. Let's push that into the "vote_option" column and the note under the table that proposes table design probably isn't relevant.

**Comment by eevui** [comment]
@jhuhnke right, so a straight vote_option with the text should be good.

How do we reconcile vote amount done by delegators, which override the default vote cast by the validator? Perhaps vote weights/amounts should be a separate table? Particularly after tallying is done by the protocol... something like `silver__governance_vote_tally`?

**Comment by eevui** [comment]
Not fun, looks like `messages` is silent about the proposal LUNA being refunded, or the grant being awarded.

**Comment by jhuhnke** [comment]
Sorry for the slow response, some spicy stuff at work on my end. I am going to request that the blockchain column stay in the table. It is used for joining to the labels table, which we are taking directly from Flipside. In the Flipside crosschain repo, there is a labels table that contains both terra classic and terra labels. So there is a chance that address might not be sufficient to join on.

**Comment by eevui** [comment]
Gotcha. Keeping `blockchain` in, this'll only ever have the value `"terra"`.

As for `vote_weight`, I guess it wouldn't be too much of a waste simply having it in as a column.
