### ISSUE TITLE
Governance Submit Proposal - Silver And Core

### ISSUE THREAD

**Issue by jhuhnke** [MetricsDAO/terra_dbt#39]
We need a silver layer for Governance Submit Proposal with a core view. This table will be downstream of the messages model (https://github.com/MetricsDAO/terra_dbt/issues/8 ) and should focus on the creation of governance proposals onto the blockchain.

### To Do
- [ ]  Assign primary & secondary analysts
- [ ]  Design the schema for this table
- [ ]  Get confirmation on schema
- [ ]  Build schema
- [ ]  Schema build review
- [ ]  Submit Pull Request for review by pod

### Direction
Governance Submit Proposals is a common curated table and many examples can be found in the Flipside data tables, most notable in the [Osmosis database](https://github.com/FlipsideCrypto/osmosis-models/blob/main/models/silver/silver__governance_submit_proposal.sql).

The suggested table design is as follows: 
 <html>
<body>

Column | Data Type | Tests | Documentation
-- | -- | -- | --
block_id | number | Unique, not null, sequence gaps, number format | Also known as block height. The block_id, which indicates the length of the blockchain, increases after the addition of each new block.
block_timestamp | timestamp | One day recent, not null, timestamp format | The date and time the block was recorded.
blockchain | string | not null, string/varchar format | The name of the blockchain.
chain_id | string | not null, string/varchar format | The version of the blockchain.
tx_id | string | not null, string/varchar format | A unique key that identifies a transaction. Called "TxHash" on block explorers.
tx_succeeded | boolean | not null | TRUE if the transaction was successful, FALSE otherwise.
proposer | string | not null, string/varchar format | The address of the wallet that is submitting the proposal.
proposal_id | number | not null, number format, no gaps test | An ordered, numerical ID that corresponds to the proposal being voted on.
proposal_type | number | not null, number format | Details what type of proposal was submitted. I.E. text proposal...

</body>
</html>

Based off Atomscan for Terra, there is a possibility that the fields "start_voting," "end_voting," and "deposit_end_time" are available in the data. If available, these three timestamp typed fields should be added to the table as well. 

### Contribution Reward
Per the S3 approach, this falls into the project category and contribution incentive will be handled through [Coordinape](https://coordinape.com/). Expected collaboration is 3-4 individuals with a primary Analyst, primary PR Reviewer and possible secondaries for either the Analyst or Review side of the work.

Issue reward pool: $1,200 in LUNA (token amount determined at time of payment)

**Comment by robel91** [comment]
I would work on this one

**Comment by robel91** [comment]
I don't think the "start_voting," "end_voting," and "deposit_end_time" fields are available in the Terra explorers. for instance, I checked this tx `9F5E797FC4C01955D89903DA41F1E7CBD55D2D95144845D11B904D28F516F6A1` in Terra_finder and Terra_Scope , but those fields are not in the logs.  In the Atomscan, the tx is not even found.

**Comment by robel91** [comment]
Also, don't you think the initial_deposit as a relevant field needs to be included in the table?
