### ISSUE TITLE
Tx Sender NULL for 11 records - Create Bespoke Test

### ISSUE THREAD

**Issue by forgxyz** [MetricsDAO/terra_dbt#43]
The below test has been failing since 10/29 with 1 record on 10/29, 9 on 10/30 and 11 today. The overall impact is marginal with just 11 records over a 3 day period but still needs fixing. The assigned analyst(s) should investigate the records with this error and work to determine root cause as well as a potential fix.

```
08:02:37  Completed with 1 error and 1 warning:
08:02:37  
08:02:37  Failure in test not_null_core__fact_transactions_TX_SENDER (models/core/core__fact_transactions.yml)
08:02:37    Got 11 results, configured to fail if != 0
08:02:37  
08:02:37    compiled SQL at target/compiled/terra/models/core/core__fact_transactions.yml/not_null_core__fact_transactions_TX_SENDER.sql
08:02:37  
08:02:37    See test failures:
  -------------------------------------------------------------
  select * from TERRA.not_null_core.fact_transactions_TX_SENDER
  -------------------------------------------------------------
```

**Comment by robel91** [comment]
I checked all those null txs in the explorer, they  all are failed txs. I am not sure if  that's the the reason or not. I tried to exclude them but the tx_gap failure will occur.

**Comment by forgxyz** [comment]
Thanks for investigating @robel91 
So - the column can legitimately be null. Let's do 2 things:
1. Turn off the null test so it stops alerting
2. Write a bespoke test checking for `not_null` only when the tx succeeded.

We can keep this issue open and use it to solve 2, but I'll remove the bug tag.

**Comment by robel91** [comment]
Ok ! sounds great @forgxyz

**Comment by eevui** [comment]
From the PR:

Terrascope can extract the tx_sender. I think the test holds up and the implementation should be fixed. That, unless we don't have that information at all from the chainwalker.
