### ISSUE TITLE
Dex LP Actions - Silver & Core

### ISSUE THREAD

**Issue by forgxyz** [MetricsDAO/terra_dbt#47]
We need a silver layer for (DEX) LP Actions with a core view. This table should includes all actions entering and exiting liquidity pools  

The silver layer implementation is up to the analyst. Often distinct DEXes cannot fit one model, so there may need to be multiple transform layers. The `core` view that is exposed for querying should follow the structure in `Direction` below.

When working on the DEX data, it would be prudent to take note if there is a mapping of pool IDs to tokens, or a label of some kind on contract deployment, to curate into a dimensional labels model.

### To Do 
- [ ]  Assign primary & secondary analysts
- [ ]  Design the schema for this table
- [ ]  Get confirmation on schema
- [ ]  Build schema
- [ ]  Schema build review
- [ ]  Submit Pull Request for review by pod

### Direction 
| Column                     | Data Type | Tests                                      | Documentation                                                                                                                                                                        |
|----------------------------|-----------|--------------------------------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| block_id                   | number    | not null, sequence gaps, number format     | Also known as block height. The block_id, which indicates the length of the blockchain, increases after the addition of each new block.                                              |
| block_timestamp            | timestamp | One day recent, not null, timestamp format | The date and time the block was recorded.                                                                                                                                            |
| blockchain                 | string    | not null, string/varchar format            | The name of the blockchain.                                                                                                                                                          |
| chain_id                   | string    | not null, string/varchar format            | The version of the blockchain.                                                                                                                                                       |
| tx_id                      | string    | not null, string/varchar format            | A unique key that identifies a transaction. Called "TxHash" on block explorers.                                                                                                      |
| tx_succeeded               | boolean   | not null                                   | TRUE if the transaction was successful, FALSE otherwise.                                                                                                                             |
| liquidity_provider_address | string    | not null, string/varchar format            | The address of user that provided or removed liquidity from the pool.                                                                                                                |
| action                     | string    | not null, string/varchar format            | Tells what action is happening in the transaction. I.E. is the user adding or removing liquidity to the pool                                                                         |
| pool_id                    | number    | not null, number format                    | Identifier for the pool within the module                                                                                                                                            |
| amount                     | number    | not null, number format                    | The amount that was used in the transaction message.                                                                                                                                 |
| currency                   | string    | not null, string/varchar format            | The currency that was used in the transaction message.                                                                                                                               |
| decimal                    | number    | not null, number format                    | Divide the amount by POW(10, decimal) to get the amount used in the transaction. This value can be NULL, as decimals are hand curated from an outside source and not found on-chain. |

### Contribution Reward
Per the S3 approach, this falls into the project category and contribution incentive will be handled through [Coordinape](https://coordinape.com/). Expected collaboration is 3-4 individuals with a primary Analyst, primary PR Reviewer and possible secondaries for either the Analyst or Review side of the work.

Issue reward pool: $1,200 in LUNA (token amount determined at time of payment)

**Comment by D0R11** [comment]
Will take this one

**Comment by eevui** [comment]
Can I sign on as secondary?
