### ISSUE TITLE
NFT Sales - Silver & Core

### ISSUE THREAD

**Issue by forgxyz** [MetricsDAO/terra_dbt#49]
We need a silver layer for NFT Market Sales with a core view.   

The silver layer implementation is up to the analyst. Often distinct NFT Marketplaces cannot fit one model, so there may need to be multiple transform layers. 
Terra projects and active marketplaces may be found on:
 - https://terrasco.pe/mainnet/projects
 - https://www.terra.money/ecosystem

The `core` view that is exposed for querying should follow the structure in `Direction` below.

### To Do 
- [ ]  Assign primary & secondary analysts
- [ ]  Design the schema for this table
- [ ]  Get confirmation on schema
- [ ]  Build schema
- [ ]  Schema build review
- [ ]  Submit Pull Request for review by pod

### Direction 
| Column           | Data Type | Tests                                      | Documentation                                                                                                                                                                        |
|------------------|-----------|--------------------------------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| block_id         | number    | not null, sequence gaps, number format     | Also known as block height. The block_id, which indicates the length of the blockchain, increases after the addition of each new block.                                              |
| block_timestamp  | timestamp | One day recent, not null, timestamp format | The date and time the block was recorded.                                                                                                                                            |
| blockchain       | string    | not null, string/varchar format            | The name of the blockchain.                                                                                                                                                          |
| chain_id         | string    | not null, string/varchar format            | The version of the blockchain.                                                                                                                                                       |
| tx_id            | string    | not null, string/varchar format            | A unique key that identifies a transaction. Called "TxHash" on block explorers.                                                                                                      |
| tx_succeeded     | boolean   | not null                                   | TRUE if the transaction was successful, FALSE otherwise.                                                                                                                             |
| purchaser        | string    | not null, string/varchar format            | The wallet address of the user purchasing the NFT                                                                                                                                    |
| seller           | string    | not null, string/varchar format            | The wallet address of the user selling the NFT                                                                                                                                       |
| sales_amount     | number    | not null, number format                    | The amount that was used in the transaction message.                                                                                                                                 |
| currency         | string    | not null, string/varchar format            | The currency that was used in the transaction message.                                                                                                                               |
| decimal          | number    | not null, number format                    | Divide the amount by POW(10, decimal) to get the amount used in the transaction. This value can be NULL, as decimals are hand curated from an outside source and not found on-chain. |
| marketplace      | string    | not null, string/varchar format            | The name of the marketplace the NFT was sold on                                                                                                                                      |
| contract_address | string    | not null, string/varchar format            | The contract address of the NFT project                                                                                                                                              |
| token_id         | number    | not null, number format                    | The ID of the NFT that was sold                                                                                                                                                      |
| unique_key       | string    | not null, string/varchar format            | The unique key of the table                                                                                                                                                          |

### Contribution Reward
Per the S3 approach, this falls into the project category and contribution incentive will be handled through [Coordinape](https://coordinape.com/). Expected collaboration is 3-4 individuals with a primary Analyst, primary PR Reviewer and possible secondaries for either the Analyst or Review side of the work.

Issue reward pool: $1,200 in LUNA (token amount determined at time of payment)

**Comment by geewynn** [comment]
I will take this one.
