### ISSUE TITLE
NFT Mints - Silver & Core

### ISSUE THREAD

**Issue by forgxyz** [MetricsDAO/terra_dbt#50]
We need a silver layer for NFT Project Mints with a core view.   

The silver layer implementation is up to the analyst. Each project mint may follow a distinct message structure, so it is advised the primary and secondary work closely on the investigation stage.

Terra projects and active marketplaces may be found on:
 - https://terrasco.pe/mainnet/projects
 - https://www.terra.money/ecosystem

The `core` view that is exposed for querying should follow the structure in `Direction` below.

### To Do 
- [ ]  Assign primary & secondary analysts
- [ ]  Design the schema for this table
- [ ]  Get confirmation on schema
- [ ]  Build schema
- [ ]  Schema build review
- [ ]  Submit Pull Request for review by pod

### Direction 
| Column           | Data Type | Tests                                      | Documentation                                                                                                                                                                        |
|------------------|-----------|--------------------------------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| block_id         | number    | not null, sequence gaps, number format     | Also known as block height. The block_id, which indicates the length of the blockchain, increases after the addition of each new block.                                              |
| block_timestamp  | timestamp | One day recent, not null, timestamp format | The date and time the block was recorded.                                                                                                                                            |
| blockchain       | string    | not null, string/varchar format            | The name of the blockchain.                                                                                                                                                          |
| chain_id         | string    | not null, string/varchar format            | The version of the blockchain.                                                                                                                                                       |
| tx_id            | string    | not null, string/varchar format            | A unique key that identifies a transaction. Called "TxHash" on block explorers.                                                                                                      |
| tx_succeeded     | boolean   | not null                                   | TRUE if the transaction was successful, FALSE otherwise.                                                                                                                             |
| minter           | string    | not null, string/varchar format            | The wallet address of the user that minted the NFT                                                                                                                                   |
| contract_address | string    | not null, string/varchar format            | The contract address of the NFT project                                                                                                                                              |
| token_id         | number    | not null, number format                    | The # of the token received in the mint                                                                                                                                              |
| mint_price       | number    | not null, number format                    | The price of the mint in tokens                                                                                                                                                      |
| currency         | string    | not null, string/varchar format            | The currency used to mint the NFT                                                                                                                                                    |
| decimal          | number    | not null, number format                    | Divide the amount by POW(10, decimal) to get the amount used in the transaction. This value can be NULL, as decimals are hand curated from an outside source and not found on-chain. |
| unique_key       | string    | not null, string / varchar format          | The unique key of the table                                                                                                                                                          |

### Contribution Reward
Per the S3 approach, this falls into the project category and contribution incentive will be handled through [Coordinape](https://coordinape.com/). Expected collaboration is 3-4 individuals with a primary Analyst, primary PR Reviewer and possible secondaries for either the Analyst or Review side of the work.

Issue reward pool: $1,200 in LUNA (token amount determined at time of payment)

**Comment by D0R11** [comment]
I'll get this one and I heard @liltims77 wants to tag along as a secondary analyst.

**Comment by liltims77** [comment]
yeah
