### ISSUE TITLE
Enhancement: Token Labels Table

### ISSUE THREAD

**Issue by forgxyz** [MetricsDAO/terra_dbt#66]
Per discussion in Discord, we can make a table out of token deployment events. This will give us the decimal, as well as other metadata, for new tokens.

[Discord thread](https://discord.com/channels/902943676685230100/1045314998513172510)

**Comment by D0R11** [comment]
Will make a PR.

**Comment by D0R11** [comment]
Proposed schema will be:

- blockchain
- block_timestamp
- tx_id
- label
- symbol
- address or contract_address
- decimals
- creator
- label_type
- label_subtype
- project_name

I made a left join of the token labels CTE to the dim address labels in core so only a few rows will have values in the dim_address_labels-specific columns, I guess that's okay? Tried to make the table as similar as the dim_tokens table in ibc fully curated mode.

**Comment by D0R11** [comment]
And use the address as the unique_key

**Comment by forgxyz** [comment]
> I made a left join of the token labels CTE to the dim address labels in core so only a few rows will have values in the dim_address_labels-specific columns, I guess that's okay? Tried to make the table as similar as the dim_tokens table in ibc fully curated mode.

Yes, i think this makes sense. We should add to the existing labels table in core, using this built silver table.

**Comment by forgxyz** [comment]
I agree with this schema. As it will be a silver model, include `_inserted_timestamp` as well for incremental loading

**Comment by D0R11** [comment]
> I agree with this schema. As it will be a silver model, include `_inserted_timestamp` as well for incremental loading

gotcha
