### ISSUE TITLE
Bug Report: Incorrect Token Label in Swaps

### ISSUE THREAD

**Issue by forgxyz** [MetricsDAO/terra_dbt#78]
Copying a bug report over from a user:

Escudos Token being mistaken as Luna
1.- No, but the problem is that another currency which isn't 'uluna' (Escudos) is labeled as 'uluna'
2.- Sample SQL
 
```sql
 select tx_id, from_currency, from_amount/pow(10,from_decimal), to_currency, to_amount/pow(10,to_decimal)
from terra.core.ez_swaps
where tx_id = '18805A207BF1750AC5742BB02224E0A031A1CFFA27E8A54A883E506C52F41C5E' 
 ```

3.- Transaction in Terrasco.pe https://terrasco.pe/mainnet/tx/18805A207BF1750AC5742BB02224E0A031A1CFFA27E8A54A883E506C52F41C5E
4.-  Escudos contract https://terrasco.pe/mainnet/address/terra1qj5hs3e86qn4vm9dvtgtlkdp550r0rayk9wpay44mfw3gn3tr8nq5jw3dg

**Comment by antonyip** [comment]
https://github.com/MetricsDAO/terra_dbt/issues/79#issuecomment-1430501646
