### ISSUE TITLE
Bug Report: Incorrect Swap Amount

### ISSUE THREAD

**Issue by forgxyz** [MetricsDAO/terra_dbt#79]
Swap amount in Luna in terra.core.ez_swaps table is incorrect on '2023-01-15'
you can compare  values on https://finder.terra.money/ and in terra.core.ez_swaps table
```sql
SELECT TX_ID, (FROM_AMOUNT)/1E6 AS AMOUNT_IN_LUNA
  FROM terra.core.ez_swaps
  WHERE FROM_CURRENCY = 'uluna' AND TO_CURRENCY!= 'uluna' AND TX_SUCCEEDED = TRUE AND BLOCK_TIMESTAMP::DATE = '2023-01-15'
  ORDER BY FROM_AMOUNT DESC LIMIT 1000
```

**Comment by amasucci13** [comment]
A Discord user (data-ticket-0733) reports that the to/from_amounts are incorrect for `execute_swap_operations` transactions, same tx type as above. 

Example txs:
1. ['F6BA9AD121E732F3A59A444837DB96F21916030C35C3720B2D9B5E75D9C7D6D0'](https://finder.terra.money/mainnet/tx/f6ba9ad121e732f3a59a444837db96f21916030c35c3720b2d9b5e75d9c7d6d0)
- Missing swap actions, to/from_amounts incorrect.

2.[ 'C6B055E23786F8AD468A5F9467BA1142987A1C56FD42E68A65132A6E740BD2D2' ](https://finder.terra.money/mainnet/tx/c6b055e23786f8ad468a5f9467ba1142987a1c56fd42e68a65132a6e740bd2d2)
- to_currency is wrong

**Comment by antonyip** [comment]
ez_swaps's table need to be reworked due to astroport executing multistep transactions now

**Comment by rainean** [comment]
Taking a look at this issue

**Comment by kaiblade** [comment]
Can more than one person work on this? I'm asking because I'm already working on fixing this issue.
